import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { LoginLayout } from "./_components/login-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AuthLayout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {
  /*for prefetching data n send it to client with query keys so queryClient doesn't fetch. */
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoginLayout>
          {children}
        </LoginLayout>
      </body>
    </html>
  );
}

export default AuthLayout;