import type { Metadata } from "next";
import "@/styles/globals.css";
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";
import { AppProvider } from "./provider";
import { getUserQueryOptions } from "@/lib/auth";
import { Share_Tech_Mono } from "next/font/google";

const font = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
  fallback: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {
  /*for prefetching data n send it to client with query keys so queryClient doesn't fetch. */
  
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(getUserQueryOptions());
  const dehydratedState = dehydrate(queryClient);
  
  return (
    <html lang="en">
      <body className={`font-arial antialiased`}>
        <AppProvider>
          <HydrationBoundary state={dehydratedState}>
            {children}
          </HydrationBoundary>
        </AppProvider>
      </body>
    </html>
  );
}

export default RootLayout;
